version: '2.4'
services:
  
  # Python Flask API (Yahoo Finacel API)
  python3:
    restart: always
    build: 
      context: ./_build/server
      dockerfile: Dockerfile
    command: python server/start_api.py
    container_name: 'PricerAPI'
    working_dir: '/root/'
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./server:/root/server
    
  # PostgreSQL install
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_USER: hogehoge
      POSTGRES_PASSWORD: password
      PGPASSWORD: hogehoge
      POSTGRES_DB: stockpricer
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always

  # pgadmin install
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: hogehoge@pgadmin4.info
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    hostname: pgadmin4
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
